from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

# ======================================================
# Request Payload Schema
# ======================================================
class ChatRequest(BaseModel):
    query: Optional[str] = Field(
        None, 
        description="The textual question or issue description submitted by the technician."
    )
    attached_image_path: Optional[str] = Field(
        None, 
        description="The local server disk path or URL of the query-time photo uploaded by the technician."
    )
    conversation_id: Optional[str] = Field(
        None, 
        description="UUID session identifier string. Omit on the first message to generate a new thread, pass it back on subsequent turns to maintain chat history."
    )

# ======================================================
# Response Child Components
# ======================================================
class SourceDocument(BaseModel):
    postgres_chunk_id: str = Field(
        ..., description="The original unique primary key matching the chunk record in PostgreSQL."
    )
    document_id: str = Field(
        ..., description="The filename or identifier of the source Siemens manual PDF."
    )
    page_id: str = Field(
        ..., description="The specific page number location inside the technical document."
    )
    section_name: Optional[str] = Field(
        None, description="The structural chapter or section header name (e.g., 'Section 4.1', 'Visual Entity')."
    )
    text: str = Field(
        ..., description="The raw textual chunk context or the extracted image diagram caption description."
    )
    similarity_score: float = Field(
        ..., description="The cosine similarity metric calculated by Qdrant (rounded to 4 decimals)."
    )

# ======================================================
# Root Response Payload Schema
# ======================================================
class ChatResponse(BaseModel):
    conversation_id: str = Field(
        ..., description="The target session identifier tracking this conversation's state in memory."
    )
    answer: str = Field(
        ..., description="The diagnostic markdown text generated by the multi-modal pipeline synthesis."
    )
    query_type: str = Field(
        ..., description="Classification category label: 'text', 'image', or 'mixed'."
    )
    sources: List[SourceDocument] = Field(
        default=[], 
        description="Array of underlying manual references extracted during the cross-retrieval pipeline execution."
    )
    metadata: Dict[str, Any] = Field(
        default={}, 
        description="Arbitrary supplementary runtime telemetry metrics (e.g., token consumption tracking, internal graph flags)."
    )