from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, List, Dict, Any

# ======================================================
# Request Payload Schema
# ======================================================
class ChatRequest(BaseModel):
    # Without this, FastAPI's /docs (Swagger UI) auto-fills every optional
    # string field with the placeholder "string" in the try-it-out example,
    # which — if left unedited — gets sent as a real value and causes
    # attached_image_path to be (wrongly) treated as a real file_id attempt,
    # producing a 400. An explicit example fixes what /docs displays.
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "query": "How do I reset a fault code F0001 on a Siemens S7-1200?",
                    "attached_image_path": None,
                    "conversation_id": None,
                }
            ]
        }
    )

    query: Optional[str] = Field(
        None,
        description="The textual question or issue description submitted by the technician."
    )
    attached_image_path: Optional[str] = Field(
        None,
        description=(
            "Optional. The file_id (UUID) returned by POST /api/v1/upload for a "
            "previously uploaded diagnostic photo. Omit or leave null for text-only "
            "questions — this is NOT required. This must be an internal file ID/UUID, "
            "NOT a raw client-supplied filesystem path or arbitrary URL, to avoid "
            "path-traversal / arbitrary-file-read risk."
        )
    )
    conversation_id: Optional[str] = Field(
        None,
        description="UUID session identifier string. Omit on the first message to generate a new thread, pass it back on subsequent turns to maintain chat history."
    )

# ======================================================
# Response Child Components
# ======================================================
class SourceDocument(BaseModel):
    postgres_chunk_id: str = Field(
        ..., description="The original unique primary key matching the chunk record in PostgreSQL."
    )
    document_id: str = Field(
        ..., description="The filename or identifier of the source Siemens manual PDF."
    )
    page_id: str = Field(
        ..., description="The specific page number location inside the technical document."
    )
    section_name: Optional[str] = Field(
        None, description="The structural chapter or section header name (e.g., 'Section 4.1', 'Visual Entity')."
    )
    text: str = Field(
        ..., description="The raw textual chunk context or the extracted image diagram caption description."
    )
    similarity_score: float = Field(
        ..., description="The cosine similarity metric calculated by Qdrant (rounded to 4 decimals)."
    )

class UploadResponse(BaseModel):
    file_id: str = Field(
        ..., description="Opaque UUID identifying the stored upload. Pass this back as `attached_image_path` on /api/v1/chat."
    )

class AvailableImage(BaseModel):
    url: str = Field(..., description="The URL or disk path of a diagram/image available to reference.")
    text: str = Field(..., description="The caption or description associated with the image.")
    document_id: str = Field(..., description="The source manual document identifier.")
    page_id: str = Field(..., description="The page number within the source document.")

# ======================================================
# Root Response Payload Schema
# ======================================================
class ChatResponse(BaseModel):
    conversation_id: str = Field(
        ..., description="The target session identifier tracking this conversation's state in memory."
    )
    answer: str = Field(
        ..., description="The diagnostic markdown text generated by the multi-modal pipeline synthesis."
    )
    query_type: str = Field(
        ..., description="Classification category label: 'text', 'image', or 'mixed'."
    )
    sources: List[SourceDocument] = Field(
        default=[],
        description="Array of underlying manual references extracted during the cross-retrieval pipeline execution."
    )
    metadata: Dict[str, Any] = Field(
        default={},
        description=(
            "Arbitrary supplementary runtime telemetry metrics (e.g., token consumption tracking, "
            "internal graph flags, and 'available_images': List[AvailableImage] surfaced directly "
            "from retrieval, independent of whether the LLM embedded them in markdown)."
        )
    )